name: WalkingParticles
main: WalkingParticles\WalkingParticles
api: ["1.13.0"]
version: 2.0.0#23
author: CyberCube-HK Team & hoyinm14mc

commands:
  walkp:
    usage: /wparticles help
    permission: walkingparticles.command.admin
    description: Admin command of WalkingParticles
    aliases: ["walkingparticles", "walkp"]
  wplist:
    usage: /wplist
    permission: walkingparticles.command.wplist
    description: WalkingParticles > Show a list of available particles
  wpget:
    usage: /wpget
    permission: walkingparticles.command.wpget
    description: WalkingParticles > Show a list of your using particles
  wppack:
    usage: /wppack <apply|get|list> <args..>
    permission: walkingparticles.command.wppack
    description: Let players to apply/get/list packs using money

permissions:
  walkingparticles:
    default: true
  walkingparticles.command:
    default: false
    children:
      walkingparticles.command.admin:
        default: op
      walkingparticles.command.wplist:
        default: true
      walkingparticles.command.wpget:
        default: true
      walkingparticles.command.wppack:
        default: true
  walkingparticles.sign.toggle:
    default: true
  walkingparticles.sign.create:
    default: op
  walkingparticles.sign.destroy:
    default: op