name: WalkingParticles
main: WalkingParticles\WalkingParticles
api: ["1.13.0", "2.0.0"]
version: 2.0.0 beta
author: CyberCube-HK Team & hoyinm14mc

commands:
  walkp:
    usage: /walkp help
    permission: walkingparticles.command.admin
    description: Admin command of WalkingParticles
    aliases: ["walkingparticles", "walkp"]
  wplist:
    usage: /wplist
    permission: walkingparticles.command.wplist
    description: WalkingParticles > Show a list of available particles
  wpget:
    usage: /wpget
    permission: walkingparticles.command.wpget
    description: WalkingParticles > Show a list of your using particles
  wppack:
    usage: /wppack <apply|get|list> <args..>
    permission: walkingparticles.command.wppack
    description: Let players to apply/get/list packs using money
  wptry:
    usage: /wptry <player>
    permission: walkingparticles.command.wptry
    description: Let players to try out a player's particle pack
  wprand:
    usage: /wprand
    permission: walkingparticles.command.wprand
    description: Toggles your random mode on/off
    aliases: ["wprandom", "wprandommode", "wprandomshow"]
  wpitem:
    usage: /wpitem
    permission: walkingparticles.command.wpitem
    description: Toggles your item mode on/off
    aliases: ["wpitemmode", "wpitemshow"]
permissions:
  walkingparticles:
    default: true
  walkingparticles.try.pay.bypass:
    default: op
  walkingparticles.command:
    default: false
    children:
      walkingparticles.command.admin:
        default: op
      walkingparticles.command.wplist:
        default: true
      walkingparticles.command.wpget:
        default: true
      walkingparticles.command.wppack:
        default: true
      walkingparticles.command.wptry:
        default: true
  walkingparticles.sign.toggle:
    default: true
  walkingparticles.sign.create:
    default: op
  walkingparticles.sign.destroy:
    default: op
